config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :campervans do
    resources :bookings, only: [:new, :create] do
      member do
      get :index_by_user
      end
    end
  end
  resources :bookings, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :campervan

  validates :start_date, :end_date, presence: true
end

app/models/campervan.rb
class Campervan < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :campervans, dependent: :destroy
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
    @van_bookings = Booking.joins(:campervan).where(user: current_user)
    @user_vans = Campervan.where(user: current_user)
  end

  def new
    @campervan = Campervan.find(params[:campervan_id])
    @booking = Booking.new
  end

  def create
    @campervan = Campervan.find(params[:campervan_id])
    @booking = Booking.new(booking_params)
    start_date = Date.parse(params[:booking][:start_date])
    end_date = Date.parse(params[:booking][:end_date])
    total_price = (end_date - start_date).to_i * @campervan.price_per_night
    @booking.total_price = total_price
    @booking.user = current_user
    @booking.campervan = @campervan
    if @booking.save
      render "confirmation"
    else
      render "new"
    end
  end

  def index_by_user
    # @user =
    @booking = Booking.where(user: current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :user_id, :campervan_id)
  end
end

app/controllers/campervans_controller.rb
def convert_date_to_number(date)
  return (date - Date.new(2020, 11, 1)).to_i
end

def convert_number_to_date(number)
  return (Date.new(2020, 11, 1) + number.days)
end

class CampervansController < ApplicationController
  before_action :set_campervan, only: %i[show destroy]

  def index
    @campervans = Campervan.all

    # filter campervans for a certain city
    if params[:search][:city].present?
      @campervans = @campervans.near(params[:search][:city], 5)
    end

    # filter campervans for a certain brand
    if params[:search][:brand].present?
      @campervans = @campervans.where(brand: params[:search][:brand])
    end

    @markers = @campervans.geocoded.map do |campervan|
      {
        lat: campervan.latitude,
        lng: campervan.longitude,
        infoWindow: render_to_string(partial: "../views/campervans/infowindow", locals: {campervan: campervan})
      }
    end

    # filter campervans available for user's dates
    if params[:search][:start_date].present?
      userStart = convert_date_to_number(Date.parse(params[:search][:start_date]))
      userEnd = convert_date_to_number(Date.parse(params[:search][:end_date]))

      # hash table of each campervan's availability (for each day) of user search dates
      # key: campervan_id
      # value: array of 1s & 0s to represent whether that day is booked
      availability = Hash.new
      Campervan.all.each do |campervan|
        availability[campervan[:id]] = Array.new(userEnd - userStart + 1, 1)
      end

      # iterate through Booking table
      # any bookings that overlap with user's search are marked as 0 for that campervan's day
      Booking.all.each do |booking|
        bookingStart = convert_date_to_number(booking[:start_date])
        bookingEnd = convert_date_to_number(booking[:end_date])
        # if the booking dates overlap with user's searched dates
        if bookingEnd >= userStart && bookingStart <= userEnd
          # determine the range of dates it overlaps on in array of availabilities
          indexStart = bookingStart < userStart ? 0 : bookingStart - userStart
          indexEnd = bookingEnd > userEnd ? userEnd - userStart : bookingEnd - userStart
          # turn those booked dates for that campervan to 0 for availability
          (indexStart..indexEnd).each do |i|
            availability[booking[:campervan_id]][i] = 0
          end
        end
      end

      # filter through campervans list
      # only keep campervans that have a 1 in their availability list
      @campervans = @campervans.select do |campervan|
        !availability[campervan[:id]].include? 0
      end
    end
  end

  def show
  end

  def new
    @campervan = Campervan.new
  end

  def create
    @campervan = Campervan.new(campervan_params)
    @campervan.user = current_user
    if @campervan.save
      redirect_to campervan_path(@campervan), alert: 'Your campervan was successfully created! 🚐'
    else
      render :new
    end
  end

  def destroy
    @campervan.destroy

    redirect_to bookings_path
  end

  private

  def campervan_params
    params.require(:campervan).permit(:title, :description, :brand, :model, :photo, :capacity, :price_per_night, :address)
  end

  def set_campervan
    @campervan = Campervan.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/confirmation.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <h1><strong>Shotgun! <%= current_user.first_name %>, you're sitting in the front seat!</strong></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-6 van-photo rotated">
      <% if @campervan.photo.attached? %>
        <%= cl_image_tag @campervan.photo.key, height: 300, width: 400, crop: :fill %>
      <% else %>
        <%= image_tag("https://i.pinimg.com/originals/65/b1/3f/65b13f6ab12de47cfcdefb32b2d67387.jpg", alt:"image", crop: :fill, height: 200, width: 250) %>
      <% end %>
      <div>
        <p><%= @campervan.title %></p>
      </div>
    </div>
    <div class="col-6 d-flex align-content-between flex-wrap">
      <div>
        <h3>Your reservation details</h3>
        <ul class="confirmation-details">
          <li> <strong><%= @booking.campervan.brand %><%= @booking.campervan.model %></strong></li>
          <li></strong>From: <%= @booking.start_date %></strong></li>
      <li></strong>To: <%= @booking.start_date %></strong></li>
  <li>Total price: <%= @booking.total_price %>€</li>
  <li>Space for up to <%= @campervan.capacity %> people</li>
</ul>
<%= link_to 'AWESOME!', bookings_path, class: "btn btn-flat btn-awesome" %>
</div>
</div>
</div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <ul class="nav list-inline tabs-underlined" id="myTab" role="tablist">
    <li role="presentation">
      <a class="nav-link tab-underlined" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
    </li>
    <li role="presentation">
      <a class="nav-link tab-underlined active" id="bookings-tab" data-toggle="tab" href="#bookings" role="tab" aria-controls="bookings" aria-selected="true">Bookings</a>
    </li>
    <li role="presentation">
      <a class="nav-link tab-underlined" id="vans-tab" data-toggle="tab" href="#vans" role="tab" aria-controls="vans" aria-selected="false">Listings</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <p>First name: <%= current_user.first_name %></p>
            <p>Last name: <%= current_user.last_name %></p>
            <p>Email address: <%= current_user.email %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade show active" id="bookings" role="tabpanel" aria-labelledby="bookings-tab">
      <div class="container">
        <h1>My Bookings</h1>
        <div class="row">
          <div class="col-6">
            <% @bookings.each do |booking| %>
              <%= link_to campervan_path(booking.campervan) do %>
                <div class="card-product mt-4">
                  <% if booking.campervan.photo.attached? %>
                    <%= cl_image_tag booking.campervan.photo.key, height: 100, width: 150, crop: :fill %>
                  <% else %>
                    <%= image_tag("https://i.pinimg.com/originals/65/b1/3f/65b13f6ab12de47cfcdefb32b2d67387.jpg", alt:"image", height: "auto", width: 100, crop: :fill) %>
                  <% end %>
                  <div class="card-product-infos">
                    <h2> <%= booking.campervan.title %> </h2>
                    <p>Pick-up: <%= booking.start_date %></p>
                    <p>Drop-off: <%= booking.end_date %></p>
                    <p><strong>Total Price: <%= booking.total_price %> €</strong></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="vans" role="tabpanel" aria-labelledby="vans-tab">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <h1>My Vans</h1>
            <div class="d-flex flew-wrap">
              <% @user_vans.each do |user_van| %>
                <%= link_to campervan_path(user_van) do %>
                  <div class="card-campervan mr-3 mb-3 m">
                    <% if user_van.photo.attached? %>
                      <%= cl_image_tag user_van.photo.key, height: 200, width: 250, crop: :fill %>
                    <% else %>
                      <%= image_tag("https://i.pinimg.com/originals/65/b1/3f/65b13f6ab12de47cfcdefb32b2d67387.jpg", alt:"image", crop: :fill, height: 200, width: 250) %>
                    <% end %>
                    <div class="card-campervan-infos m-3">
                      <h2><%= user_van.title %></h2>
                      <p><%= user_van.description %></p>
                      <p class="bold"><%= user_van.brand %> <%= user_van.model %></p>
                      <h2 class="card-pricing"><%= user_van.price_per_night %>€/night</h2>
                      <%= link_to campervan_path(user_van), method: :delete, data: {confirm: "Delete #{user_van.title}?"} do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <h1>Your Van's Bookings</h1>
            <div class="d-flex flew-wrap flex-column">
              <% @van_bookings.each do |van_booking| %>
                <div class="card-campervan mr-3 mb-3">
                  <% if van_booking.campervan.photo.attached? %>
                    <%= cl_image_tag van_booking.campervan.photo.key, height: 200, width: 250, crop: :fill %>
                  <% else %>
                    <%= image_tag("https://i.pinimg.com/originals/65/b1/3f/65b13f6ab12de47cfcdefb32b2d67387.jpg", alt:"image", crop: :fill, height: 200, width: 250) %>
                  <% end %>
                  <div class="card-campervan-infos align-items-center justify-content-center">
                    <h2 class="">Total price: <%= van_booking.total_price %>€</h2>
                    <p class="">Pickup: <%= van_booking.start_date %></p>
                    <p class="">Dropoff: <%= van_booking.end_date %></p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class=container>
  <h1>New Booking</h1>
  <div class="row">
    <div class="col-4">
      <%= simple_form_for([@campervan, @booking]) do |f| %>
        <%= f.input :start_date, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker"} %>
        <%= f.button :submit, 'BOOK NOW!', class: "bnt btn-flat" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Booking Confirmation</h1>


 <h3>Your booking is confirmed</h3>

  <%= link_to booking.campervan.title, campervan_path(booking.campervan)  %>
  <% if booking.campervan.photo.attached? %>
    <%= cl_image_tag booking.campervan.photo.key, height: 300, width: 400, crop: :fill %>
  <% else %>
    There is no photo yet!
    <%= image_tag("https://i.pinimg.com/originals/65/b1/3f/65b13f6ab12de47cfcdefb32b2d67387.jpg", alt:"image", crop: :fill, height: 500, class: "card-img-top rounded") %>
  <% end %>
  <p>Pick-up date: <%= booking.start_date %></p>
  <p>Drop-off date: <%= booking.end_date %></p>
  <p>Total Price: <%= booking.total_price %></p>

app/views/campervans/_info_window.html.erb
<h2><%= campervan.title %></h2>
<p><%= campervan.address %></p>

app/views/campervans/_infowindow.html.erb
<h2><%= campervan.title %></h2>
<p><%= campervan.address %></p>

app/views/campervans/index.html.erb
<div class="search-bar">
  <div class="container search-bar-home">
  <%= simple_form_for :search, url: campervans_path, method: :get do |f| %>
    <%= f.input :city, input_html: {value: params[:search][:city]} %>
    <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :brand, collection: ['Volkswagen', 'Nissan', 'Mercedes', 'Ford', 'Honda', 'Toyota'], input_html: {selected: params[:search][:brand]} %>
    <%= f.submit "Search", class: "btn btn-flat-form" %>
  <% end %>
  </div>
</div>
<div class="container">
  <h1 class="my-4">Campervans</h1>

  <div class="row justify-content-center">
    <div class="col-6">
      <% @campervans.each do |campervan| %>
        <%= link_to campervan_path(campervan) do %>
          <div class="card-campervan mb-4">
            <% if campervan.photo.attached? %>
              <%= cl_image_tag campervan.photo.key, height: 200, width: 250, crop: :fill %>
            <% else %>
              <%= image_tag("https://i.pinimg.com/originals/65/b1/3f/65b13f6ab12de47cfcdefb32b2d67387.jpg", alt:"image", crop: :fill, height: 200, width: 250) %>
            <% end %>

            <div class="card-campervan-infos m-3">
              <h2><%= campervan.title %></h2>
              <p><%= campervan.description %></p>
              <p class="bold"><%= campervan.brand %> <%= campervan.model %></p>
              <h2 class="card-pricing"><%= campervan.price_per_night %>€/night</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-6">
      <div id="map"
       style="width: 100%; height: 600px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

<script>document.querySelector("option[value='<%= params[:search][:brand] %>']").selected = true</script>

app/views/campervans/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6">
      <h1>Advertise a camper van</h1>
      <div class="form-group">
        <%= simple_form_for(@campervan) do |f| %>
          <%= f.label :title %>
          <%= f.input_field :title, class: "form-control" %>
          <%= f.label :description %>
          <%= f.input_field :description, class: "form-control"%>
          <%= f.input :brand, collection: ['Volkswagen', 'Nissan', 'Mercedes', 'Ford', 'Honda', 'Toyota'], class: "form-control" %>
          <%= f.input :model, collection: ['Multivan', 'California', 'C-Max', 'Tourneo', 'Sprinter', 'Vaneo', 'Bluebird', 'Interstar' ], class: "form-control"%>
          <%= f.label :capacity %>
          <%= f.input_field :capacity, class: "form-control"%>
          <%= f.label :address %>
          <%= f.input_field :address, class: "form-control"%>
          <%= f.label :price_per_night %>
          <%= f.input_field :price_per_night, class: "form-control"%>
          <%= f.input :photo, as: :file %>
          <%= f.submit 'Post ad', class: "btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/campervans/show.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <h1><strong><%= @campervan.title %></strong></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-4 van-photo">
      <% if @campervan.photo.attached? %>
        <%= cl_image_tag @campervan.photo.key, height: 300, width: 400, crop: :fill %>
      <% else %>
        <%= image_tag("https://i.pinimg.com/originals/65/b1/3f/65b13f6ab12de47cfcdefb32b2d67387.jpg", alt:"image", crop: :fill, height: 200, width: 250) %>
      <% end %>
      <div>
        <p>Offered by <%= @campervan.user.first_name %></p>
      </div>
    </div>
    <div class="col-3 d-flex align-content-between flex-wrap">
      <div>
        <h3>Facts</h3>
        <strong>
          <%= @campervan.brand %>
          <%= @campervan.model %>
        </strong>
        <p>Capacity: <%= @campervan.capacity %> people</p>
        <p><%= @campervan.price_per_night %>&euro; per night</p>
      </div>
      <div>
        <%= link_to 'BOOK NOW!', new_campervan_booking_path(@campervan), class: "btn btn-flat btn-book" %>
      </div>
    </div>
    <div class="col-3 van-features">
      <h3>Features</h3>
      <p><%= @campervan.features %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campervans</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<div>
 <p><center>Explore campervans rentals near you</center></p>
</div>

<div class="search-bar">
  <div class="container search-bar-home">
  <%= simple_form_for :search, url: campervans_path, method: :get do |f| %>
    <%= f.input :city %>
    <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.input :brand, collection: ['Volkswagen', 'Nissan', 'Mercedes', 'Ford', 'Honda', 'Toyota'] %>
    <%= f.submit "Search", class: "btn btn-flat-form" %>
  <% end %>
  </div>
</div>

<div>
<p><center>Search by city</center></p>
</div>

<div class="container my-4">
  <div class="cards justify-content-between my-4" >
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1540224485413-4c7939106f3a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)">
      Berlin
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1587226008387-636795e5aa72?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)">
      Rennes
    </div>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1481141373687-f63a2873d0be?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)">
      Boulder
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1515876305430-f06edab8282a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80);">
  <div class="container">
    <h1>Shotgun<strong></strong></h1>
    <p>Live life in the front seat</p>
  </div>
  <div class="arrow-down-centre">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="76" height="76" viewBox="0 0 24 24" stroke-width="1" stroke="#ffffff " fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
      <polyline points="6 9 12 15 18 9" />
    </svg>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer container">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_map.html.erb
<div id='map' style='width: 400px; height: 300px;'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoibGhzNDA0NSIsImEiOiJja2g0cDdwdnYwYW82MnJvOTk5Ynp1MTZzIn0.VYUq7vgLO62fXHHg1kzJWA';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
    center: [-74.5, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
});
</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky ">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Hi, #{current_user.first_name}", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "shiva.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", bookings_path, class: "dropdown-item" %>
              <%= link_to "List a van", new_campervan_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchform.html.erb
<form>
  <div class="form-row">
    <div class="col-6">
      <input type="text" class="form-control" placeholder="City">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="Start">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="End">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="Capacity">
    </div>
  </div>
</form>
<div></div>